apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: resume
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: resume-frontend
        image: genai-resume-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
