apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: frontend-deployment
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
