apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.mongodb.persistence.storage }}
  hostPath:
    path: /data
